name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}
          MATTERMOST_WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }} 
        run: |
          echo "$KEY" > ec2key.pem
          chmod 600 ec2key.pem
          tar --exclude='.git' --warning=no-file-changed -czf code.tar.gz . || true
          scp -i ec2key.pem -o StrictHostKeyChecking=no code.tar.gz $USER@$HOST:/home/$USER/python-ec2-github-actions/
          ssh -i ec2key.pem -o StrictHostKeyChecking=no -f $USER@$HOST "nohup bash -c '
            sudo ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime &&
            cd /home/$USER/python-ec2-github-actions &&
            if [ -f app.pid ]; then
              kill -9 \$(cat app.pid) || true
              rm -f app.pid
            fi &&
            pkill -f \"bash -c .*python3 src/main.py\" || true &&
            tar -xzf code.tar.gz &&
            (python3 -m pip --version || python3 -m ensurepip --upgrade || sudo yum install -y python3-pip) &&
            python3 -m pip install --upgrade pip &&
            pip3 install -r requirements.txt &&
            nohup env TZ=Asia/Seoul MATTERMOST_WEBHOOK_URL=\"$MATTERMOST_WEBHOOK_URL\" python3 src/main.py </dev/null > app.log 2>&1 & echo \$! > app.pid
          ' & disown"