name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy with SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            sudo ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
            cd /home/${{ secrets.EC2_USER }}/python-ec2-github-actions
            git pull origin main
            python3 -m pip install --upgrade pip
            pip3 install -r requirements.txt
            nohup env TZ=Asia/Seoul python3 src/main.py > app.log 2>&1 &